# services:
#   airflow:
#     image: apache/airflow:2.8.1
#     container_name: airflow
#     ports:
#       - 8080:8080
#     env_file:
#       - ../.env
#     volumes:
#       - ./dags:/opt/airflow/dags
#       - ../requirements.txt:/requirements.txt
#     command: >
#       bash -c "
#       pip install --no-cache-dir -r /requirements.txt &&
#       airflow db migrate &&
#       airflow users create --username admin --password samarth108 --firstname Samarth --lastname Kaul --role Admin --email disssamarth@gmail.com || true &&
#       exec airflow webserver"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: spotify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.10.4
    container_name: airflow-webserver
    ports:
      - 8080:8080
    env_file:
      - ../.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ../requirements.txt:/requirements.txt
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow db migrate &&
      airflow users create --username admin --password samarth108 --firstname Samarth --lastname Kaul --role Admin --email disssamarth@gmail.com || true &&
      exec airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.10.4
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    env_file:
      - ../.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ../requirements.txt:/requirements.txt
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      exec airflow scheduler"
